In [1]:
import json
from datetime import datetime
from models import (Base, session,
                    Shopping,Products, engine)
import re

def clean_shoping(text):
    text = text.split("\n")
    total = 0
    merchant_name = text[0].strip()


    for i in range(0, len(text) - 1):
        if "SUMA PLN" in text[i]:
            total = re.sub(",",".",re.sub("SUMA PLN", "", text[i]).strip())



    return total, merchant_name;


def clean_products(text):
    staff = []
    
    text = text.split("\n")
    
    for i in range(0, len(text) - 1):
        text[i] = text[i].strip()

        if text[i] == "PARAGON FISKALNY":
            j = i + 1
            
            while "SPRZEDAZ OPODATKOWANA" not in text[j]:
                staff.append(text[j])
               
                j += 1
   
    
    dict = {}

    for i in range(0, len(staff) ):
        
        match = re.sub(r'[ ]+[A-Z]?[ ]+',' X ',staff[i].strip())
        print(match)
        match = re.split(r' X ', match)
        print(match)
        
       
         
      
        
        if (len(match) == 2) and bool(re.search("[\d ]+[x*X][\d, ]+[\w]", match[1])):
            
            match[1] = re.sub(r'(szt.)?','',match[1])
            dict[match[0]] = re.findall(r'[\d+,(.)?]+[A-C]?', match[1].strip())
            dict[match[0]][2] = re.sub(r'[A?B?C?]?', '', dict[match[0]][2])
            dict[match[0]][0] = re.sub(r',', '.', dict[match[0]][0])
            dict[match[0]][1] = re.sub(r',', '.', dict[match[0]][1])
            dict[match[0]][2] = re.sub(r',', '.', dict[match[0]][2])
    print(dict)
    return dict


def load(file):
    #file = "response1.json" wroc do tej wersji
    path = file

    with open(file, "r") as f:
        data = json.load(f)


    text = data["receipts"][0]["ocr_text"]
    print(text)
    date = re.findall(r'(20\d\d-\d\d-\d\d)', text)
    products = clean_products(text)
    shopping_info = clean_shoping(text)



    #
    # add_shopping = Shopping(merchant_name=shopping_info[1],
    #                         total=float(shopping_info[0]),
    #                         date=datetime.strptime(date[0] ,"%Y-%m-%d"),
    #                         filename="None")
    #
    #
    # session.add(add_shopping)
    # session.commit()
    #
    #
    # for product in products:
    #     print(products[product])
    #     add_product = Products(item=product,
    #                             price=float(products[product][1]),
    #                             quantity=float(products[product][0]),
    #                             total =float(products[product][2]),
    #                             shopping_id=session.query(Shopping).order_by(Shopping.id.desc()).first().id)
    #
    #     session.add(add_product)
    #     session.commit()
    #

In [1]:
file = "response.json"
load(file)

NameError: name 'load' is not defined

In [3]:
file = "zabka.json"
load(file)

                                 Sklep Zabka Z5252
                                   Anna Płaszczyk
                                   44-117 Gliwice
                                   ul. Jowisza la
              NIP 6312700874                                 nr: 207762
                          PARAGON FISKALNY
              NAPOJ MONSTER 0,51-A                   1szt. x6,99 6,99A
              KEBAB ROLLO 280g-B                   1szt. x13,99 13,99B
              OPUST KEBAB ROLLO 280g-B                          -7,09B
              SPRZEDAZ OPODATKOWANA A                             6,99
              SPRZEDAZ OPODATKOWANA B                             6,90
              PTU A 23%                                           1,31
              PTU B 8%                                            0.51
              SUMA PTU                                            1.82
              SUMA PLN                                      13,89
              ROZLICZENIE PŁATNOŚCI
              INNA Karta kred.                              13.89 PLN
                    #25252-1 kasjer_3                2022-11-15 13:55
                       9607ED4070794DF 791F6FB74ED50302843AE00D
                                     EA0 2001618259
                                   Nr sys 165486
      REDMI NOTE 8 PRO
  28
        QUAD CAMERA
NAPOJ MONSTER 0,51-A X 1szt. x6,99 6,99A
['NAPOJ MONSTER 0,51-A', '1szt. x6,99 6,99A']
KEBAB ROLLO 280g-B X 1szt. x13,99 13,99B
['KEBAB ROLLO 280g-B', '1szt. x13,99 13,99B']
OPUST KEBAB ROLLO 280g-B X -7,09B
['OPUST KEBAB ROLLO 280g-B', '-7,09B']
{'NAPOJ MONSTER 0,51-A': ['1', '6.99', '6.99'], 'KEBAB ROLLO 280g-B': ['1', '13.99', '13.99']}

In [4]:
file = "biedronka.json"
load(file)

                                   Biedronka
                                   Codziennie niskie ceny
                     Sklep 4296 ul. Toszecka 129, 44-117 GL
                      iwiceJeronimo Martins Polska S.A.ul.
             Zniwna 5, 62-025 Kostrzyn
                               NIP 779-10-11-327
             2022-11-14 18:18                                290900
                        PARAGON FISKALNY
            TorbaPapierowalszt       A                 1 x0,99 0,99A
            Nap Coca-Cola 0,5L       A                 1 x3,79 3,79A
              Rabat                                           -0,60
                                                               3,19A
            ArielKapsKolor 20szt     A               1 x29,99 29,99A
            Ser żółty 135g           D                 1 x5,39 5,390
            SzynMorlin200-250g       D                 1 x8,49 8,490
            SokJabManVitFresh1       D                 1 x4,99 4,99D
            KiełŚląsSerKW450 g       D               1 x14,94 14,94D
            HerLipMięZCytrus20TB     B                 1 x4,99 4,99B
            Pomid gał luz            D            0,345 x11.99 4,140
            Cebula Zółta Luz         D             0,085 x3,99 0,34D
             Rabat                                            -0.09
                                                               0,250
            Woda gaz Cechi2L A                         1 x2,19 2,19A
              Rabat                                           -0.50
                                                               1,69A
            SPRZEDAZ OPODATKOWANA A                             35,86
           PTU A 23,00 %                                         6,71
           SPRZEDAZ OPODATKOWANA B                               4,99
           PTU B 8,00 %                                          0.37
          SPRZEDAZ OPODATKOWANA D %                              38,20
          SUMA PTU                                                7,08
          SUMA PLN                                          79,05
          00257 #Kasa 16 Kasjer nr 4                 2022-11-14 18:18
                   OAB207AE2F43B21BEDA2C4551F5F79EFC04A8422
                              PCCH 1903117561
  O REDMI NOTE 8 PRO
  28
      AI QUAD CAMERA
TorbaPapierowalszt X 1 x0,99 0,99A
['TorbaPapierowalszt', '1 x0,99 0,99A']
Nap Coca-Cola 0,5L X 1 x3,79 3,79A
['Nap Coca-Cola 0,5L', '1 x3,79 3,79A']
Rabat X -0,60
['Rabat', '-0,60']
3,19A
['3,19A']
ArielKapsKolor 20szt X 1 x29,99 29,99A
['ArielKapsKolor 20szt', '1 x29,99 29,99A']
Ser żółty 135g X 1 x5,39 5,390
['Ser żółty 135g', '1 x5,39 5,390']
SzynMorlin200-250g X 1 x8,49 8,490
['SzynMorlin200-250g', '1 x8,49 8,490']
SokJabManVitFresh1 X 1 x4,99 4,99D
['SokJabManVitFresh1', '1 x4,99 4,99D']
KiełŚląsSerKW450 g X 1 x14,94 14,94D
['KiełŚląsSerKW450 g', '1 x14,94 14,94D']
HerLipMięZCytrus20TB X 1 x4,99 4,99B
['HerLipMięZCytrus20TB', '1 x4,99 4,99B']
Pomid gał luz X 0,345 x11.99 4,140
['Pomid gał luz', '0,345 x11.99 4,140']
Cebula Zółta Luz X 0,085 x3,99 0,34D
['Cebula Zółta Luz', '0,085 x3,99 0,34D']
Rabat X -0.09
['Rabat', '-0.09']
0,250
['0,250']
Woda gaz Cechi2L X 1 x2,19 2,19A
['Woda gaz Cechi2L', '1 x2,19 2,19A']
Rabat X -0.50
['Rabat', '-0.50']
1,69A
['1,69A']
{'TorbaPapierowalszt': ['1', '0.99', '0.99'], 'Nap Coca-Cola 0,5L': ['1', '3.79', '3.79'], 'ArielKapsKolor 20szt': ['1', '29.99', '29.99'], 'Ser żółty 135g': ['1', '5.39', '5.390'], 'SzynMorlin200-250g': ['1', '8.49', '8.490'], 'SokJabManVitFresh1': ['1', '4.99', '4.99'], 'KiełŚląsSerKW450 g': ['1', '14.94', '14.94'], 'HerLipMięZCytrus20TB': ['1', '4.99', '4.99'], 'Pomid gał luz': ['0.345', '11.99', '4.140'], 'Cebula Zółta Luz': ['0.085', '3.99', '0.34'], 'Woda gaz Cechi2L': ['1', '2.19', '2.19']}

In [5]:
file = "stokrotka.json"
load(file)

                       Stokrotka Sp z o.o.
                          20-209 Lublin, ul. Projektowa 1
                             Supermarket Stokrotka 027
                          44-117 Gliwice, ul. Kopernika 16
                      NIP 7121008323                  nr: 22756
                          PARAGON FISKALNY
                      A REKLAMOWKA FIRMOWA        1 x1,19 1,19A
                      B KETCHUP TORTEX 470G       1 x4,99 4,99B
                      D KOZIELSKI CHLEB BAL       1 x4,60 4,600
                      D MASŁO EKSTRA POLSKI       1.x7,99 7,990
                       D PIEROZKI GYOZA Z KU      1 x8,49 8,49D
                       A PIWO NAMYSŁÓW PILS       1 x3,69 3,69A
                       A NAPOJ COCA-COLA 850      1 x4,79 4,79A
                       D MANDARYNKA KG CT     0,355 x9,99 3,550
                       D JOGURT SKYR 150G OS      2 x2,99 5,980
                       D MLEKO UHT MU! 1,5%       1 x3,79 3,790
                       D MORLINY POLĘDWICA Z      1 x5,29 5,290
                       D SER ZOŁTY PLASTRY 1      1 x5,99 5,990
                       SPRZEDAZ OPODATKOWANA A             9,67
                       SPRZEDAZ OPODATKOWANA B              4,99
                        SPRZEDAZ OPODATKOWANA D            45,68
                        PTU A 23%                           1.81
                        PTU B 8%                            0,37
                        PTU 0%                              0,00
                        SUMA PTU                            2.18
                        SUMA PLN                      60,34
                        ROZLICZENIE PŁATNOŚCI
                        KARTA MAGNETYCZNA              60,34 PLN
                        0012146 #04 38752       2022-11-08 15:40
                        77815F56038F5FF6F 807F86113A5CF0984F6F 9F5
                                           2001630588
                         BDO 000022694
      REDMI NOTE 8 PROIEBIORCO LICZBA PO "Nr sys
                                  PARAGONU
      AI QUAD CAMERA
                                          22/0027/04/028019
A REKLAMOWKA FIRMOWA X 1 x1,19 1,19A
['A REKLAMOWKA FIRMOWA', '1 x1,19 1,19A']
B KETCHUP TORTEX 470G X 1 x4,99 4,99B
['B KETCHUP TORTEX 470G', '1 x4,99 4,99B']
D KOZIELSKI CHLEB BAL X 1 x4,60 4,600
['D KOZIELSKI CHLEB BAL', '1 x4,60 4,600']
D MASŁO EKSTRA POLSKI X 1.x7,99 7,990
['D MASŁO EKSTRA POLSKI', '1.x7,99 7,990']
D PIEROZKI GYOZA X KU X 1 x8,49 8,49D
['D PIEROZKI GYOZA', 'KU', '1 x8,49 8,49D']
A PIWO NAMYSŁÓW PILS X 1 x3,69 3,69A
['A PIWO NAMYSŁÓW PILS', '1 x3,69 3,69A']
A NAPOJ COCA-COLA 850 X 1 x4,79 4,79A
['A NAPOJ COCA-COLA 850', '1 x4,79 4,79A']
D MANDARYNKA KG CT X 0,355 x9,99 3,550
['D MANDARYNKA KG CT', '0,355 x9,99 3,550']
D JOGURT SKYR 150G OS X 2 x2,99 5,980
['D JOGURT SKYR 150G OS', '2 x2,99 5,980']
D MLEKO UHT MU! 1,5% X 1 x3,79 3,790
['D MLEKO UHT MU! 1,5%', '1 x3,79 3,790']
D MORLINY POLĘDWICA X 1 x5,29 5,290
['D MORLINY POLĘDWICA', '1 x5,29 5,290']
D SER ZOŁTY PLASTRY 1 X 1 x5,99 5,990
['D SER ZOŁTY PLASTRY 1', '1 x5,99 5,990']
{'A REKLAMOWKA FIRMOWA': ['1', '1.19', '1.19'], 'B KETCHUP TORTEX 470G': ['1', '4.99', '4.99'], 'D KOZIELSKI CHLEB BAL': ['1', '4.60', '4.600'], 'A PIWO NAMYSŁÓW PILS': ['1', '3.69', '3.69'], 'A NAPOJ COCA-COLA 850': ['1', '4.79', '4.79'], 'D MANDARYNKA KG CT': ['0.355', '9.99', '3.550'], 'D JOGURT SKYR 150G OS': ['2', '2.99', '5.980'], 'D MLEKO UHT MU! 1,5%': ['1', '3.79', '3.790'], 'D MORLINY POLĘDWICA': ['1', '5.29', '5.290'], 'D SER ZOŁTY PLASTRY 1': ['1', '5.99', '5.990']}

In [6]:
match = ['Nap Coca-Cola 0,5L', '1 x3,79 3,79A']
print(re.search("[\d ]+[x*X][\d, ]+[\w]", match[1]))

<re.Match object; span=(0, 13), match='1 x3,79 3,79A'>

In [7]:
match = ['NAPOJ MONSTER 0,51-A', '1szt. x6,99 6,99A']
print(re.search("[\d ]+[x*X][\d, ]+[\w]", match[1]))

<re.Match object; span=(5, 17), match=' x6,99 6,99A'>

In [11]:
import json 
import re

path = 'json/response.json'

with open(path, "r") as f:
        data = json.load(f)


text = data["receipts"][0]["ocr_text"]

text = text.split("\n")

location = []

for i in range(0, len(text)-1):

        

        
         

         if text[i].strip() == "PARAGON FISKALNY":
                #print(' '.join(location))
                break

                         Biedronka
                         Codziennie niskie ceny
           Sklep 4296 ul. Toszecka 129, 44-117 GL
            iwiceJeronimo Martins Polska S.A.ul.
  Zniuna 5, 62-025 Kostrzyn
 2022-12-15 16:13                                  301862
              PARAGON FISKALNY

In [2]:
import pandas as pd
import psycopg2


conn = psycopg2.connect(user="postgres",
                        password="qwest1",
                        host="localhost",
                        database="Finances")

query = "select * from locations;"

df = pd.read_sql(query, conn)

print(df)

    id      location
0    1  Jelenia Góra
1    2       Legnica
2    3       Wrocław
3    4     Wałbrzych
4    5     Bydgoszcz
..  ..           ...
61  62        Leszno
62  63        Poznań
63  64      Koszalin
64  65      Szczecin
65  66   Świnoujście

[66 rows x 2 columns]

C:\Users\skyri\AppData\Local\Temp\ipykernel_27148\1111338349.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)